name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
      with:
        lfs: true
    
    - name: Checkout LFS
      run: git lfs checkout

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make
    
    - name: Test Board
      working-directory: ${{github.workspace}}/build/tests
      run: ./board_test
