name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cmake --build ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_TESTS=ON

    - name: Make
      working-directory: ${{github.workspace}}/build/tests
      run: make
    
    -name: Test
      working-directory: ${{github.workspace}}/build/bin
      run: ./test